[package]
name = "aliyun-oss-client"
version = "0.7.5"
edition = "2021"
resolver = "2"
license = "MIT"
description = "an aliyun oss client"
keywords = ["aliyun", "oss", "sdk"]
repository= "https://github.com/tu6ge/oss"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[[example]]
name = "bucket"
required-features = ["blocking"]

[[example]]
name = "buckets"
required-features = ["blocking"]

[[example]]
name = "delete_file"
required-features = ["blocking"]

[[example]]
name = "objects"
required-features = ["blocking"]

[[example]]
name = "plugin"
required-features = ["plugin"]

[[example]]
name = "put_file"
required-features = ["blocking"]

[features]
default = ["plugin"]
plugin = []
blocking = ["reqwest/blocking"]

[dependencies]
hmac = "^0.12"
sha1 = "^0.10"
base64 = "^0.13"
reqwest = {version ="^0.11"}
chrono = "^0.4"
quick-xml = "^0.24"
infer = "^0.9"
thiserror = "^1"
anyhow = "^1"
futures = "^0.3"
urlencoding = "2.1.0"
async-trait = "0.1.57"
regex = "^1"

[dev-dependencies]
dotenv = "0.15.0"
assert_matches = "1.5.0"
tokio = { version = "1.19.2", features = ["rt","macros","rt-multi-thread"] }

