[package]
name = "aliyun-oss-client"
version.workspace = true
edition.workspace = true
resolver = "2"
license.workspace = true
description = "an aliyun oss client"
keywords = ["aliyun", "oss", "sdk"]
repository.workspace = true
rust-version = "1.62"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
all-features = true

[workspace]
members = ["oss_derive"]

[workspace.package]
version = "0.9.4"
edition = "2021"
license = "MIT"
repository = "https://github.com/tu6ge/oss-rs"

[[example]]
name = "bucket"
required-features = ["blocking"]

[[example]]
name = "buckets"
required-features = ["blocking"]

[[example]]
name = "delete_file"
required-features = ["blocking"]

[[example]]
name = "objects"
required-features = ["blocking"]

[[example]]
name = "put_file"
required-features = ["blocking", "put_file"]

[[sts]]
name = "sts"
required-features = ["sts"]

[features]
default = [
  #"blocking",
  "sts",
  "put_file"
]
blocking = ["reqwest/blocking"]
sts = []
put_file = ["infer"]
bench = []

[dependencies]
hmac = "^0.12"
sha1 = "^0.10"
base64 = "^0.13"
reqwest = {version ="^0.11"}
chrono = "^0.4"
quick-xml = "^0.26"
infer = {version = "^0.11", optional = true}
thiserror = "^1"
anyhow = "^1"
futures = {version = "^0.3"}
urlencoding = "^2"
async-trait = "^0.1"
http="^0.2"
async-stream = "^0.3"
futures-core = "^0.3"
futures-util = "^0.3"

[dependencies.oss_derive]
version = "0.9.4"
path = "./oss_derive"

[dev-dependencies]
dotenv = "0.15.0"
assert_matches = "1.5.0"
tokio = { version = "1.19.2", features = ["rt","macros","rt-multi-thread"] }
mockall = "0.11.2"
mockall_double= "0.3.0"
#faux = "^0.1"
reqwest = {version ="^0.11", features = ["blocking"]}

[build-dependencies]
rustc_version = "0.4.0"
