[package]
name = "aliyun-oss-client"
version = "0.2.6"
edition = "2021"
resolver = "2"
license = "MIT"
description = "an aliyun oss client"
keywords = ["aliyun", "oss", "sdk"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
hmac = "0.12.1"
sha1 = "0.10.1"
base64 = "0.13.0"
reqwest = {version ="0.11.10", features= ["blocking"]}
chrono = "0.4"
quick-xml = "0.23.0"
url = "2.2.2"
infer = "0.8.0"
thiserror = "1.0"

[dev-dependencies]
dotenv = "0.15.0"
assert_matches = "1.5.0"
