[package]
name = "aliyun-oss-client"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
hmac = "0.12.1"
sha1 = "0.10.1"
base64 = "0.13.0"
reqwest = {version ="0.11.10", features= ["blocking"]}
chrono = "0.4"
serde = "^1"
serde_derive = "^1"
serde-xml-rs = "0.5.1"

[dev-dependencies]
dotenv = "0.10.1"
