[package]
name = "aliyun-oss-client"
version = "0.4.4"
edition = "2021"
resolver = "2"
license = "MIT"
description = "an aliyun oss client"
keywords = ["aliyun", "oss", "sdk"]
repository= "https://github.com/tu6ge/oss"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
hmac = "^0.12"
sha1 = "^0.10"
base64 = "^0.13"
reqwest = {version ="^0.11", features= ["blocking"]}
chrono = "^0.4"
quick-xml = "^0.23"
url = "^2"
infer = "^0.8"
thiserror = "^1"
anyhow = "^1"

[dev-dependencies]
dotenv = "0.15.0"
assert_matches = "1.5.0"

