[package]
name = "demo1"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oss = {path="../..", package="aliyun-oss-client"}
dotenv = "0.10.1"
