name: Publish to Cargo

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'publish'

    environment: cargo

    steps:
      - uses: actions/checkout@master

      # v0.1.15 目前版本
      - name: Cache publish-action bin
        id: cache-publish-action
        uses: actions/cache@v3
        env:
          cache-name: cache-publish-changelog-action
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v0.1.15

      - name: Install publish-action
        if: steps.cache-publish-action.outputs.cache-hit != 'true'
        run: |
          cargo install publish-action --version=0.1.15
          cargo install changelog
      
      - name: Run publish-action
        id: publish-action
        run: 
          publish-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      
      - name: echo Output
        run: |
          echo "new_version result:"
          echo ${{steps.publish-action.outputs.new_version}}
          echo "publish result:"
          echo ${{steps.publish-action.outputs.publish}}

      - name: Update Changelog.md
        run: |
          changelog -o Changelog.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog.md
  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Install cargo-tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-tarpaulin

      # - name: Run cargo tarpaulin
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: tarpaulin
      #     args: --output-dir coverage --out Lcov
      
      # - name: Publish to Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
