name: Publish to Cargo

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'publish'

    environment: cargo

    steps:
      - uses: actions/checkout@master

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-publish-action
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/publish-action
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Install cargo-local-install
        run:
          cargo install cargo-local-install

      - name: Install publish-action
        run:
          cargo local-install --locked publish-action --root ~/publish-action
      
      - name: Run publish-action
        run:
          ./home/runner/publish-action/bin/publish-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      
      # - name: Publish to Crates.io
      #   uses: tu6ge/publish-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
