name: Publish to Cargo

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'publish'

    steps:
      - uses: actions/checkout@master

      - name: Install and Build
        run:
          cargo install publish-action
      
      - name: Run publish-action
        run:
          publish-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # - name: Publish to Crates.io
      #   uses: tu6ge/publish-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
